- name: Create Dotfile Parent Directories
  file:
    dest: "{{ ansible_env.HOME }}/{{ item.to | dirname }}"
    state: directory
  loop: "{{ symlinks }}"

- name: Symlink Dotfiles
  file:
    src: "{{ inventory_dir }}/{{ item.from }}"
    dest: "{{ ansible_env.HOME }}/{{ item.to }}"
    state: link
  loop: "{{ symlinks }}"

- name: Check if Rust is installed
  shell: rustup --version
  register: rust_installed
  ignore_errors: true

- name: Download Rustup Script
  get_url:
    url: https://sh.rustup.rs/
    dest: /tmp/rustup.sh
    mode: 0755
  when: rust_installed.rc > 0

- name: Run Rustup
  shell: /tmp/rustup.sh -y
  when: rust_installed.rc > 0

- name: Discover installed packages
  shell: cargo install --list
  register: installed_packages

- name: Install Common Programs from crates.io
  shell: cargo install --verbose "{{ item }}"
  loop: "{{ cargo_packages }}"
  when: not item in installed_packages.stdout
