- name: Install System Packages
  package:
    name:
      - bazel
      - blueman
      - bluez-utils
      - clang
      - cmake
      - dmenu
      - docker
      - dunst
      - feh
      - file-roller
      - firefox
      - freerdp
      - git
      - go
      - htop
      - hugo
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
      - lastpass-cli
      - lld
      - llvm
      - neovim
      - network-manager-applet
      - networkmanager
      - nmap
      - noto-fonts-emoji
      - noto-fonts-extra
      - noto-fonts
      - ntfs-3g
      - obs-studio
      - pavucontrol
      - python-pip
      - python
      - rofi
      - seahorse
      - signal-desktop
      - strace
      - thunar-volman
      - thunar
      - traceroute
      - ttf-inconsolata
      - udiskie
      - unrar
      - virtualbox
      - vlc
      - wget
      - xclip
      - xorg-xev
      - xorg-xinput
      - xorg-xrandr
      - xorg-xrdb
      - zsh
  become: true
