# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

plugins=(git history-substring-search)

source $ZSH/oh-my-zsh.sh

# User configuration

export EDITOR='nvim'
alias ls=exa

prompt() {
    PS1="$(powerline-rs --shell zsh $?)"
}
precmd_functions+=(prompt)

eval $(go env | grep GO | awk '{ print("export", $0) }')

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/.yarn/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$PATH:$HOME/.dotnet/tools

# Set up the android NDK variables
source /etc/profile.d/android-ndk.sh

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

export TERMINAL=alacritty

# Let GPG know which TTY it is used by
export GPG_TTY=$(tty)

eval `ssh-agent` >/dev/null

# We want to disable incremental complation when using sccache
if cargo config get -Z unstable-options -- build.rustc-wrapper 2>/dev/null | grep -Fq "build.rustc-wrapper"; then
    export CARGO_INCREMENTAL=0
fi

# Prevents rust-analyzer from spawning infinite docker images
# while compiling librunecoral
export RUNECORAL_DIST_DIR=$HOME/Documents/hotg-ai/librunecoral/dist

# Load NVM
[ -f /usr/share/nvm/init-nvm.sh ] && source /usr/share/nvm/init-nvm.sh
